# Generated by Django 5.0.7 on 2024-07-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dedline_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
