# Generated by Django 5.0.7 on 2024-07-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_task_dedline_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dedline_datetime',
            new_name='deadline_datetime',
        ),
    ]
